// genvectors.mjs — regenerate the FROZEN protocol-v2 test vectors pinned in
// test-node/crypto.test.js. Run with:  node test/genvectors.mjs
//
// From fixed inputs (F, CEK, IVs, salt, password, plaintext) it recomputes the
// canonical AAD, the Argon2id password key, the KEK, both access proofs (and
// their stored hashes), the wrapped CEK and the content ciphertext for the
// no-password and password branches, then prints a ready-to-paste `VECTORS`
// object.
//
// This is a DELIBERATE, spec-first step. Any protocol/format/AAD change MUST
// update SPEC.md first, then rerun this to regenerate the vectors — never edit
// the pinned hexes by hand. Refresh both places:
//   node test/genvectors.mjs > test/vectors.expected.txt
// and paste the same output over the VECTORS object in test-node/crypto.test.js.
// tools/verify-vectors.py re-derives the same bytes independently (Python).

import { keySchedule, aesGcmEncrypt, aesGcmDecrypt, proofHash } from '../public/js/crypto.js';
import { argon2idRaw } from '../public/js/kdf.js';
import { buildAAD } from '../public/js/format.js';
import { hex, b64urlFromBytes, utf8, fromUtf8 } from '../public/js/bytes.js';

// ── Fixed inputs shared by the frozen vectors (must match crypto.test.js) ────
const seq = (start, n) => Uint8Array.from({ length: n }, (_, i) => (start + i) & 0xff);
const fill = (v, n) => new Uint8Array(n).fill(v);

const F = seq(0, 32);
const CEK = seq(0x20, 32);
const ivc = fill(0x11, 12);
const ivw = fill(0x22, 12);
const salt = fill(0x33, 16);
const VEC_PLAINTEXT = 'secbin vector — zero knowledge ✓';

const CASES = {
  nopw: {
    adata: { alg: 'A256GCM', kdf: 'hkdf', iter: 0, comp: 'none', fmt: 'plaintext', bar: false,
             ivc: b64urlFromBytes(ivc), ivw: b64urlFromBytes(ivw), skdf: '' },
    password: '',
  },
  pw: {
    adata: { alg: 'A256GCM', kdf: 'argon2id-hkdf', iter: 3, comp: 'none', fmt: 'plaintext', bar: false,
             ivc: b64urlFromBytes(ivc), ivw: b64urlFromBytes(ivw), skdf: b64urlFromBytes(salt) },
    password: 'correct horse',
  },
};

async function computeVector(c) {
  const aad = buildAAD(c.adata);
  const pwIkm = c.password ? await argon2idRaw(utf8(c.password.normalize('NFC')), salt, { t: c.adata.iter }) : new Uint8Array(0);
  const { kek, linkProof, keyProof } = await keySchedule(F, pwIkm);
  const wk = await aesGcmEncrypt(kek, ivw, CEK, aad);
  const contentKey = await crypto.subtle.importKey('raw', CEK, { name: 'AES-GCM' }, false, ['encrypt', 'decrypt']);
  const ct = await aesGcmEncrypt(contentKey, ivc, utf8(VEC_PLAINTEXT), aad);

  if (hex(await aesGcmDecrypt(kek, ivw, wk, aad)) !== hex(CEK)) throw new Error('self-check failed: CEK unwrap');
  if (fromUtf8(await aesGcmDecrypt(contentKey, ivc, ct, aad)) !== VEC_PLAINTEXT) throw new Error('self-check failed: decrypt');

  return {
    adata: c.adata,
    password: c.password,
    aadHex: hex(aad),
    pwIkmHex: hex(pwIkm),
    linkProof: b64urlFromBytes(linkProof),
    keyProof: b64urlFromBytes(keyProof),
    lh: await proofHash(b64urlFromBytes(linkProof)),
    kh: await proofHash(b64urlFromBytes(keyProof)),
    wkHex: hex(wk),
    ctHex: hex(ct),
  };
}

const q = (s) => `'${s}'`;

function printVector(name, v) {
  const a = v.adata;
  console.log(`  ${name}: {`);
  console.log(`    adata: { alg: ${q(a.alg)}, kdf: ${q(a.kdf)}, iter: ${a.iter}, comp: ${q(a.comp)}, fmt: ${q(a.fmt)}, bar: ${a.bar},`);
  console.log(`             ivc: b64urlFromBytes(ivc), ivw: b64urlFromBytes(ivw), skdf: ${a.skdf === '' ? "''" : 'b64urlFromBytes(salt)'} },`);
  console.log(`    password: ${q(v.password)},`);
  for (const k of ['aadHex', 'pwIkmHex', 'linkProof', 'keyProof', 'lh', 'kh', 'wkHex', 'ctHex']) {
    console.log(`    ${k}: ${q(v[k])},`);
  }
  console.log('  },');
}

const vectors = {};
for (const [name, c] of Object.entries(CASES)) vectors[name] = await computeVector(c);

console.log('// FROZEN vectors — generated by test/genvectors.mjs and pinned here. Any');
console.log('// change to the protocol MUST update SPEC.md and regenerate these deliberately.');
console.log('const VECTORS = {');
for (const [name, v] of Object.entries(vectors)) printVector(name, v);
console.log('};');
