// crypto.test.js — the v2 cryptographic protocol (SPEC.md §2–§5, §11).
// Runs in plain Node (Web Crypto + streams + WebAssembly for Argon2id), the same
// primitives the browser and CLI use. The Worker never runs this code.
import { describe, it, expect } from 'vitest';
import {
  encryptPaste, deriveAccess, openPaste, unwrapCek, decryptContent, keySchedule,
  aesGcmEncrypt, aesGcmDecrypt, proofHash, gzip, gunzip,
  PasswordRequired, DecryptError, MAX_PLAINTEXT,
} from '../public/js/crypto.js';
import { argon2idRaw } from '../public/js/kdf.js';
import { buildAAD, validateCreate, validatePaste, validateHead } from '../public/js/format.js';
import { hex, b64urlFromBytes, bytesFromB64url, randomBytes, utf8, fromUtf8 } from '../public/js/bytes.js';

const seq = (start, n) => Uint8Array.from({ length: n }, (_, i) => (start + i) & 0xff);
const fill = (v, n) => new Uint8Array(n).fill(v);
const unhex = (h) => Uint8Array.from((h.match(/../g) || []).map((b) => parseInt(b, 16)));

// ── Fixed inputs shared by the frozen vectors (test/genvectors.mjs) ──────────
const F = seq(0, 32);
const CEK = seq(0x20, 32);
const ivc = fill(0x11, 12);
const ivw = fill(0x22, 12);
const salt = fill(0x33, 16);
const VEC_PLAINTEXT = 'secbin vector — zero knowledge ✓';

// FROZEN vectors — generated by test/genvectors.mjs and pinned here. Any
// change to the protocol MUST update SPEC.md and regenerate these deliberately.
const VECTORS = {
  nopw: {
    adata: { alg: 'A256GCM', kdf: 'hkdf', iter: 0, comp: 'none', fmt: 'plaintext', bar: false,
             ivc: b64urlFromBytes(ivc), ivw: b64urlFromBytes(ivw), skdf: '' },
    password: '',
    aadHex: '73656362696e2f76320a616c673d4132353647434d0a6b64663d686b64660a697465723d300a636f6d703d6e6f6e650a666d743d706c61696e746578740a6261723d300a6976633d455245524552455245524552455245520a6976773d496949694969496949694969496949690a736b64663d0a',
    pwIkmHex: '',
    linkProof: '_Vnj_mPEy7Rfo4gcxzAQVj7qk5pcmYuf_zr4zhxPpvI',
    keyProof: 'PUtbfpZsnAofo48AgCujYJgXpTyWEwjA6FP_pqoyJf4',
    lh: 'FmBQhWBJ-cjh0vXydV6MCOtjOgXU_VBPZEi-17n2EZg',
    kh: 'PiuWCHxXmt9k8y4XvYGKmDPWJWfeAJDEyAt4fofi1xM',
    wkHex: 'd9e7a014c3a392c5966af7779d60e3bc2e9686650a869c23c4094d31877c8f7d2989219dc8beed306c706b03a65fc772',
    ctHex: '405811c70399338336f6bcb6bfd2c568f53db90206cf40be135ac57b48bb16302ff78e4a501cf3a0e065dd6b175eda39f7ddc9f6',
  },
  pw: {
    adata: { alg: 'A256GCM', kdf: 'argon2id-hkdf', iter: 3, comp: 'none', fmt: 'plaintext', bar: false,
             ivc: b64urlFromBytes(ivc), ivw: b64urlFromBytes(ivw), skdf: b64urlFromBytes(salt) },
    password: 'correct horse',
    aadHex: '73656362696e2f76320a616c673d4132353647434d0a6b64663d6172676f6e3269642d686b64660a697465723d330a636f6d703d6e6f6e650a666d743d706c61696e746578740a6261723d300a6976633d455245524552455245524552455245520a6976773d496949694969496949694969496949690a736b64663d4d7a4d7a4d7a4d7a4d7a4d7a4d7a4d7a4d7a4d7a4d770a',
    pwIkmHex: '5058052c0eae847dbbc4aed52f04a94eb2391d2b7f9e8e8d364212d56b1c0594',
    linkProof: '_Vnj_mPEy7Rfo4gcxzAQVj7qk5pcmYuf_zr4zhxPpvI',
    keyProof: 'bXLv8D9lrS25K7LB5QL58cg4Uhu3dR7mYX6HSm_9MZw',
    lh: 'FmBQhWBJ-cjh0vXydV6MCOtjOgXU_VBPZEi-17n2EZg',
    kh: 'RuZY6BzxAcm5y7XoUGG4hsII0R6yHvK9yDWu5RiZ-3U',
    wkHex: '84bcabc0071dec1b956778fa4b1f2acb0f3e42bae809d5a4839d1a2bd142d8c1643ebe3a621d6673736f924d858f7d04',
    ctHex: '405811c70399338336f6bcb6bfd2c568f53db90206cf40be135ac57b48bb16302ff78e4a3284e62245cce0f81ad31500db7818a1',
  },
};

describe('Argon2id (RFC 9106) known answer', () => {
  it('matches the phc-winner-argon2 reference vector (password/somesalt, t=2, m=64 MiB, p=1)', async () => {
    const out = await argon2idRaw(utf8('password'), utf8('somesalt'), { t: 2, mKiB: 65536, p: 1 });
    expect(hex(out)).toBe('09316115d5cf24ed5a15a31a3ba326e5cf32edc24702987c02b6566f61913cf7');
  });
});

describe('frozen v2 test vectors', () => {
  for (const [name, v] of Object.entries(VECTORS)) {
    it(`${name}: AAD, password key, proofs, wrap and ciphertext match`, async () => {
      const aad = buildAAD(v.adata);
      expect(hex(aad)).toBe(v.aadHex);
      const pwIkm = v.password ? await argon2idRaw(utf8(v.password), salt, { t: v.adata.iter }) : new Uint8Array(0);
      expect(hex(pwIkm)).toBe(v.pwIkmHex);
      const { kek, linkProof, keyProof } = await keySchedule(F, pwIkm);
      expect(b64urlFromBytes(linkProof)).toBe(v.linkProof);
      expect(b64urlFromBytes(keyProof)).toBe(v.keyProof);
      expect(await proofHash(v.linkProof)).toBe(v.lh);
      expect(await proofHash(v.keyProof)).toBe(v.kh);
      const wk = await aesGcmEncrypt(kek, ivw, CEK, aad);
      expect(hex(wk)).toBe(v.wkHex);
      expect(hex(await aesGcmDecrypt(kek, ivw, wk, aad))).toBe(hex(CEK));
      const key = await crypto.subtle.importKey('raw', CEK, { name: 'AES-GCM' }, false, ['encrypt', 'decrypt']);
      expect(hex(await aesGcmEncrypt(key, ivc, utf8(VEC_PLAINTEXT), aad))).toBe(v.ctHex);
      expect(fromUtf8(await aesGcmDecrypt(key, ivc, unhex(v.ctHex), aad))).toBe(VEC_PLAINTEXT);
    });
  }
});

// Simulates the server: releases {v,ct,wk,adata,meta} only for matching proofs.
async function serverOpen(body, access) {
  const clean = validateCreate(body);
  const ok = (await proofHash(access.linkProof)) === clean.acc.lh && (await proofHash(access.keyProof)) === clean.acc.kh;
  if (!ok) return null;
  const { acc: _acc, ...paste } = clean;
  return validatePaste(paste);
}

describe('encrypt → derive access → open', () => {
  it('no-password round-trips and emits a valid v2 create body', async () => {
    const { body, fragment } = await encryptPaste({ text: 'hello, secbin' });
    expect(() => validateCreate(body)).not.toThrow();
    expect(body.v).toBe(2);
    expect(body.adata.kdf).toBe('hkdf');
    const head = validateHead({ v: body.v, adata: body.adata, meta: body.meta });
    const access = await deriveAccess({ adata: head.adata, fragment });
    const paste = await serverOpen(body, access);
    expect((await openPaste({ paste, access })).text).toBe('hello, secbin');
  });

  it('round-trips every format and the view-limit flag', async () => {
    for (const fmt of ['plaintext', 'code', 'markdown', 'files']) {
      for (const bar of [false, true]) {
        const text = `body ${fmt} ${bar}`;
        const { body, fragment } = await encryptPaste({ text, fmt, bar });
        const access = await deriveAccess({ adata: body.adata, fragment });
        const out = await openPaste({ paste: await serverOpen(body, access), access });
        expect(out).toEqual({ text, fmt, bar });
      }
    }
  });

  it('never puts the fragment, the proofs or the KEK material in the body', async () => {
    const { body, fragment } = await encryptPaste({ text: 'secret' });
    const access = await deriveAccess({ adata: body.adata, fragment });
    const s = JSON.stringify(body);
    expect(s).not.toContain(fragment);
    expect(s).not.toContain(access.linkProof);
    expect(s).not.toContain(access.keyProof);
  });
});

describe('password key hierarchy + proofs (SPEC.md §2)', () => {
  it('uses Argon2id and opens only with the right fragment AND password', async () => {
    const { body, fragment } = await encryptPaste({ text: 'top secret', password: 'hunter2', t: 1 });
    expect(body.adata.kdf).toBe('argon2id-hkdf');
    expect(body.adata.iter).toBe(1);
    const access = await deriveAccess({ adata: body.adata, fragment, password: 'hunter2' });
    expect((await openPaste({ paste: await serverOpen(body, access), access })).text).toBe('top secret');
  });

  it('a wrong password keeps the link proof but fails the key proof', async () => {
    const { body, fragment } = await encryptPaste({ text: 'x', password: 'pw', t: 1 });
    await expect(deriveAccess({ adata: body.adata, fragment })).rejects.toBeInstanceOf(PasswordRequired);
    const bad = await deriveAccess({ adata: body.adata, fragment, password: 'wrong' });
    expect(await proofHash(bad.linkProof)).toBe(body.acc.lh);
    expect(await proofHash(bad.keyProof)).not.toBe(body.acc.kh);
    expect(await serverOpen(body, bad)).toBeNull();
  });

  it('a wrong fragment fails the link proof (and the unwrap)', async () => {
    const { body } = await encryptPaste({ text: 'x', password: 'pw', t: 1 });
    const wrong = await deriveAccess({ adata: body.adata, fragment: b64urlFromBytes(fill(0x99, 32)), password: 'pw' });
    expect(await proofHash(wrong.linkProof)).not.toBe(body.acc.lh);
    await expect(unwrapCek({ adata: body.adata, wk: body.wk, kek: wrong.kek })).rejects.toBeInstanceOf(DecryptError);
  });

  it('rejects malformed fragments before any derivation', async () => {
    const { body } = await encryptPaste({ text: 'x' });
    for (const fragment of ['', 'not base64!', b64urlFromBytes(fill(1, 31))]) {
      await expect(deriveAccess({ adata: body.adata, fragment })).rejects.toBeInstanceOf(DecryptError);
    }
  });

  it('NFD and NFC forms of the same password derive the same key', async () => {
    const nfc = 'café';
    const nfd = 'café';
    const { body, fragment } = await encryptPaste({ text: 'across devices', password: nfd, t: 1 });
    const access = await deriveAccess({ adata: body.adata, fragment, password: nfc });
    expect((await openPaste({ paste: await serverOpen(body, access), access })).text).toBe('across devices');
  });
});

describe('authentication / tamper (AAD + ciphertext binding)', () => {
  const make = () => encryptPaste({ text: 'authentic' });
  const open = async (body, fragment) => {
    const access = await deriveAccess({ adata: body.adata, fragment });
    const { acc: _acc, ...paste } = body;
    return openPaste({ paste, access });
  };
  it('flipping an authenticated adata field breaks decryption', async () => {
    for (const mutate of [
      (b) => { b.adata.bar = true; },
      (b) => { b.adata.fmt = 'markdown'; },
      (b) => { b.adata.comp = b.adata.comp === 'gzip' ? 'none' : 'gzip'; },
    ]) {
      const { body, fragment } = await make();
      mutate(body);
      await expect(open(body, fragment)).rejects.toBeInstanceOf(DecryptError);
    }
  });
  it('flipping a ciphertext byte breaks decryption', async () => {
    const { body, fragment } = await make();
    const ct = bytesFromB64url(body.ct);
    ct[0] ^= 0x01;
    body.ct = b64urlFromBytes(ct);
    await expect(open(body, fragment)).rejects.toBeInstanceOf(DecryptError);
  });
  it('swapping the IV breaks decryption', async () => {
    const { body, fragment } = await make();
    body.adata.ivc = b64urlFromBytes(fill(0x00, 12));
    await expect(open(body, fragment)).rejects.toBeInstanceOf(DecryptError);
  });
  it('a v1 record is rejected outright', async () => {
    const { body } = await make();
    const { acc: _acc, ...paste } = body;
    expect(() => validatePaste({ ...paste, v: 1 })).toThrow(/unsupported version/);
  });
});

describe('compression', () => {
  it('compresses compressible content and round-trips', async () => {
    const text = 'x'.repeat(50000);
    const { body, fragment } = await encryptPaste({ text });
    expect(body.adata.comp).toBe('gzip');
    const access = await deriveAccess({ adata: body.adata, fragment });
    const { acc: _acc, ...paste } = body;
    expect((await openPaste({ paste, access })).text).toBe(text);
  });
  it('rejects oversized plaintext before encryption', async () => {
    await expect(encryptPaste({ text: 'a'.repeat(MAX_PLAINTEXT + 1) })).rejects.toThrow(/too large/);
  });
  it('aborts a gzip bomb that exceeds the output cap', async () => {
    const bomb = await gzip(fill(0, 200000));
    await expect(gunzip(bomb, 1000)).rejects.toBeInstanceOf(DecryptError);
  });
  it('rejects malformed gzip input', async () => {
    await expect(gunzip(fill(0xab, 64))).rejects.toBeInstanceOf(DecryptError);
  });
});

describe('decryptContent with a directly unwrapped CEK', () => {
  it('unwrap → decrypt matches openPaste', async () => {
    const { body, fragment } = await encryptPaste({ text: 'split me' });
    const access = await deriveAccess({ adata: body.adata, fragment });
    const cek = await unwrapCek({ adata: body.adata, wk: body.wk, kek: access.kek });
    expect((await decryptContent({ adata: body.adata, ct: body.ct, cek })).text).toBe('split me');
  });
});

describe('base64url canonicity — fail closed on aliasing encodings', () => {
  it('accepts canonical encodings and rejects aliases / bad alphabet', () => {
    expect(Array.from(bytesFromB64url('Zg'))).toEqual([0x66]);
    expect(Array.from(bytesFromB64url('Zm8'))).toEqual([0x66, 0x6f]);
    for (const bad of ['Zh', 'AB', 'Zm9', 'AAB', 'A_', 'AA_', 'Zg=', 'Z g', 'Zm9vY', 'a+b/']) {
      expect(() => bytesFromB64url(bad), bad).toThrow(/invalid base64url/);
    }
    for (const s of ['', 'AA', 'Zg', 'Zm8', 'Zm9v', b64urlFromBytes(randomBytes(31))]) {
      expect(b64urlFromBytes(bytesFromB64url(s))).toBe(s);
    }
  });
});
