#!/usr/bin/env node
// vendor.mjs — reproducibly (re)build the vendored third-party browser assets.
//
//   node tools/vendor.mjs
//
// Fetches the pinned npm tarballs with `npm pack`, verifies each tarball's
// SHA-256 against the pin below (fail closed on mismatch), and writes:
//
//   public/js/vendor/argon2.js        hash-wasm's Argon2 UMD build, re-wrapped as
//                                     an ES module (header/footer only; the
//                                     library body is byte-for-byte upstream)
//   public/js/vendor/pdfjs/…          pdf.js "legacy" display + worker builds (polyfilled
//                                     for current browsers), its wasm
//                                     image decoders, standard fonts and cmaps
//   public/js/qrcode.js               qrcode-generator's UMD build, byte-for-byte
//                                     (its MIT notice is in the file header; the
//                                     CLI copy cli/vendor/qrcode.cjs is synced by
//                                     cli/scripts/sync-shared.mjs)
//
// Never hand-edit the outputs; bump the version + pin here and re-run instead.
// The pins are recorded again in public/THIRD-PARTY-NOTICES.md.
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { cp, mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const PINS = {
  'hash-wasm': { version: '4.12.0', sha256: '1db32a125fb46177932ec8ac438d3cd8214ebdfaccb5d6611b657d88eb586f92' },
  'pdfjs-dist': { version: '6.3.289', sha256: '06f25e887adc6489f04c9fcb14198c77e4e5623a59a0bba5c4cea5838a4f1241' },
  'qrcode-generator': { version: '2.0.4', sha256: '02e2e18a99a90b02dad940851f59b7c3c5fd1ab79cbdece8595cb06328878159' },
};

async function fetchPackage(tmp, name) {
  const { version, sha256 } = PINS[name];
  const out = execFileSync('npm', ['pack', `${name}@${version}`, '--silent'], { cwd: tmp }).toString().trim().split('\n').pop();
  const tgz = path.join(tmp, out);
  const digest = createHash('sha256').update(await readFile(tgz)).digest('hex');
  if (digest !== sha256) throw new Error(`${name}@${version}: tarball sha256 ${digest} != pinned ${sha256}`);
  const dir = path.join(tmp, name);
  await mkdir(dir, { recursive: true });
  execFileSync('tar', ['xzf', tgz, '-C', dir]);
  return path.join(dir, 'package');
}

// The UMD wrapper starts with `!function(A,I){…}(this,(function(A){` and ends
// with `}));`. Replace just that shell so the factory populates a local object
// that we re-export; the factory body is untouched.
function umdToEsm(src) {
  const start = src.indexOf('!function(');
  const factory = src.indexOf('(this,(function(A){', start);
  if (start < 0 || factory < 0 || !src.trimEnd().endsWith('}));')) throw new Error('unexpected hash-wasm UMD shape');
  const banner = src.slice(0, start);
  const body = src.slice(factory + '(this,'.length, src.trimEnd().length - 2); // "(function(A){…})"
  return `${banner}// ES-module re-wrap generated by tools/vendor.mjs — do not edit.\n`
    + `const hashwasm = {};\n${body}(hashwasm);\n`
    + 'export const argon2id = hashwasm.argon2id;\n';
}

const tmp = await mkdtemp(path.join(os.tmpdir(), 'secbin-vendor-'));
try {
  const hw = await fetchPackage(tmp, 'hash-wasm');
  const vendorDir = path.join(root, 'public', 'js', 'vendor');
  await mkdir(vendorDir, { recursive: true });
  const argon = umdToEsm(await readFile(path.join(hw, 'dist', 'argon2.umd.min.js'), 'utf8'));
  await writeFile(path.join(vendorDir, 'argon2.js'), argon);
  await cp(path.join(hw, 'LICENSE'), path.join(vendorDir, 'argon2.LICENSE'));

  const pdf = await fetchPackage(tmp, 'pdfjs-dist');
  const pdfDir = path.join(vendorDir, 'pdfjs');
  await rm(pdfDir, { recursive: true, force: true });
  await mkdir(pdfDir, { recursive: true });
  await cp(path.join(pdf, 'legacy', 'build', 'pdf.min.mjs'), path.join(pdfDir, 'pdf.min.mjs'));
  await cp(path.join(pdf, 'legacy', 'build', 'pdf.worker.min.mjs'), path.join(pdfDir, 'pdf.worker.min.mjs'));
  for (const d of ['wasm', 'standard_fonts', 'cmaps']) await cp(path.join(pdf, d), path.join(pdfDir, d), { recursive: true });
  await cp(path.join(pdf, 'LICENSE'), path.join(pdfDir, 'LICENSE'));

  const qr = await fetchPackage(tmp, 'qrcode-generator');
  await cp(path.join(qr, 'dist', 'qrcode.js'), path.join(root, 'public', 'js', 'qrcode.js'));

  const sha = async (p) => createHash('sha256').update(await readFile(p)).digest('hex');
  console.log('argon2.js           ', await sha(path.join(vendorDir, 'argon2.js')));
  console.log('pdfjs/pdf.min.mjs   ', await sha(path.join(pdfDir, 'pdf.min.mjs')));
  console.log('pdfjs/pdf.worker.min.mjs', await sha(path.join(pdfDir, 'pdf.worker.min.mjs')));
  console.log('qrcode.js           ', await sha(path.join(root, 'public', 'js', 'qrcode.js')));
} finally {
  await rm(tmp, { recursive: true, force: true });
}
